# Generated by Django 3.2.4 on 2021-06-25 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='foodMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodtype', models.CharField(choices=[('1', 'Veg'), ('2', 'Non-Veg')], max_length=10)),
                ('cuisine', models.CharField(blank=True, choices=[('1', 'Soup'), ('2', 'Salad'), ('3', 'Appetizers'), ('4', 'Italian Mainfare'), ('5', 'Mexican Mainfare'), ('6', 'Pastas'), ('7', 'Pizzas'), ('8', 'Rice'), ('9', 'Fondue'), ('10', 'Desserts')], max_length=50)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('price', models.IntegerField(null=True)),
                ('newest', models.BooleanField(default=False)),
                ('recommended', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Food Menu',
            },
        ),
    ]
